version: '3.8'

services:
  assistente-imobiliario:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ./data:/app/data
      - ./rag/.env:/app/rag/.env
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8080 